# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# This file is used by icons rake task to download SVG icons from Tabler
# Keys description:
#   - name: destination icon name
#     svg: source icon name from Github repository
#     style: outline (default) or filled

- name: my-page
  svg: layout-dashboard
- name: logout
  svg: logout
- name: info-circle
  svg: info-circle
- name: adjustments
  svg: adjustments
- name: user-scan
  svg: user-scan
- name: help-circle
  svg: help
- name: user-screen
  svg: user-screen
- name: device-analytics
  svg: device-analytics
- name: chevrons-up
  svg: chevrons-up